apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password123
  MONGO_INITDB_DATABASE: TodoApp
  MONGODB_URI: "mongodb://admin:password123@mongo:27017/TodoApp?authSource=admin" # No good for prod, but i keep it here
