apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: llm-chat
  labels:
    app: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: backend # container name
          image: chat-backend:latest
          imagePullPolicy: Never  # Use local image from Minikube
          envFrom:
            - configMapRef:
                name: chat-backend-config
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5