apiVersion: v1
kind: Service
metadata:
    name: chat-backend
    namespace: llm-chat
    labels:
        app: chat-backend
spec:
  type: NodePort
  selector:
    app: chat-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
      nodePort: 30800