apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: llm-chat
  labels:
    app: chat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: frontend # container name
        image: chat-frontend:latest
        imagePullPolicy: Never  # Use local image from Minikube
        env:
          - name: VITE_BACKEND_URL
            value: "http://localhost:8000"
        ports:
        - containerPort: 5173
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 5
          periodSeconds: 5
