apiVersion: v1
kind: Service
metadata:
    name: chat-frontend
    namespace: llm-chat
    labels:
        app: chat-frontend
spec:
  type: NodePort
  selector:
    app: chat-frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      name: http
      nodePort: 30173